spring:
  profiles:
    active: prod
  application:
    name: ai-summary-service

  ai:
    openai:
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: "llama-3.1-8b-instant"
          temperature: 0.3
          stream-usage: false
    retry:
      max-attempts: 1

  kafka:
    consumer:
      group-id: ai-summary-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "com.gts.aisummary.global.kafka.dto"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "com.gts.aisummary.global.kafka.dto.SummaryRequestMessage"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  swagger-ui:
    try-it-out-enabled: true
